# Generated by Django 6.0.7 on 2026-08-04 03:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('drug_product_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('drug_name', models.CharField(max_length=200)),
                ('ingredient_code', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'drug',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('hospital_code', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('hospital_name', models.CharField(max_length=100)),
                ('address', models.CharField(blank=True, max_length=200)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('phone', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'hospital',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('member_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('license_no', models.CharField(blank=True, max_length=30)),
                ('department', models.CharField(default='정신건강의학과', max_length=50)),
                ('joined_at', models.DateField()),
                ('left_at', models.DateField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
                ('hospital', models.ForeignKey(db_column='hospital_code', on_delete=django.db.models.deletion.PROTECT, to='patients.hospital')),
            ],
            options={
                'db_table': 'doctor',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('patient_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
                ('gender', models.CharField(choices=[('M', '남'), ('F', '여'), ('U', '미상')], default='U', max_length=1)),
                ('birth_date', models.DateField()),
                ('height_cm', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('is_pregnant', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(db_column='hospital_code', on_delete=django.db.models.deletion.PROTECT, to='patients.hospital')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
            },
        ),
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('intent', models.CharField(choices=[('부작용', '부작용'), ('복약', '복약'), ('일반질문', '일반질문')], max_length=10)),
                ('started_at', models.DateTimeField()),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'chat_session',
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('prescription_id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('prescribed_at', models.DateField()),
                ('diagnosis', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('hospital', models.ForeignKey(db_column='hospital_code', on_delete=django.db.models.deletion.PROTECT, to='patients.hospital')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
            options={
                'db_table': 'prescription',
            },
        ),
        migrations.CreateModel(
            name='PrescriptionDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seq', models.IntegerField()),
                ('dosage_instruction', models.CharField(max_length=100)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('start_date', models.DateField()),
                ('expected_end_date', models.DateField(blank=True, null=True)),
                ('drug', models.ForeignKey(db_column='drug_product_code', on_delete=django.db.models.deletion.PROTECT, to='patients.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.prescription')),
            ],
            options={
                'db_table': 'prescription_detail',
            },
        ),
        migrations.CreateModel(
            name='DosingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_at', models.DateTimeField()),
                ('taken_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('done', '복용'), ('missed', '놓침'), ('skipped', '건너뜀'), ('pending', '대기')], default='pending', max_length=10)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescription_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.prescriptiondetail')),
            ],
            options={
                'db_table': 'dosing_log',
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('free_text', '자유문진'), ('scale', '척도')], max_length=20)),
                ('chief_complaint', models.TextField()),
                ('onset', models.CharField(blank=True, max_length=200)),
                ('symptom_pattern', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('aggravating_factor', models.TextField(blank=True)),
                ('scale_name', models.CharField(blank=True, max_length=50)),
                ('scale_score', models.IntegerField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('suspected_drugs', models.JSONField(blank=True, null=True)),
                ('reported_at', models.DateTimeField()),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.chatsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.prescription')),
            ],
            options={
                'db_table': 'symptom_log',
            },
        ),
        migrations.AddConstraint(
            model_name='prescriptiondetail',
            constraint=models.UniqueConstraint(fields=('prescription', 'seq'), name='uq_prescription_seq'),
        ),
        migrations.AddIndex(
            model_name='symptomlog',
            index=models.Index(fields=['patient', '-reported_at'], name='idx_patient_time'),
        ),
    ]
