# Generated by Django 6.0.7 on 2026-08-04 05:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=13, verbose_name='전화번호'),
        ),
    ]
