# Generated by Django 6.0.7 on 2026-08-04 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='average_sleep_time',
            field=models.TimeField(blank=True, null=True, verbose_name='평균 취침시간'),
        ),
        migrations.AddField(
            model_name='patient',
            name='average_wake_time',
            field=models.TimeField(blank=True, null=True, verbose_name='평균 기상시간'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_smoker',
            field=models.BooleanField(blank=True, null=True, verbose_name='흡연 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='meal_pattern',
            field=models.CharField(blank=True, choices=[('regular', '규칙적'), ('irregular', '불규칙적'), ('less_than_2', '하루 2끼 이하'), ('skip', '식사를 자주 거름')], max_length=20, null=True, verbose_name='식사 습관'),
        ),
        # ===== [추가] Prescription -> PrescriptionDetail 역참조 이름을 "details"로 지정 =====
        # views.py에서 prescription.details / .prefetch_related("details__drug") 처럼
        # "details"라는 이름으로 역참조하는데, related_name이 없어서 AttributeError가 났던 것을 수정.
        # (원래는 별도 0003 마이그레이션이었는데, 팀원이 만든 이 0003과 leaf가 갈라져서
        #  충돌이 났었기 때문에 이 파일 안으로 병합함)
        migrations.AlterField(
            model_name='prescriptiondetail',
            name='prescription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='patients.prescription'),
        ),
        # ===== [추가] 끝 =====
    ]