# Generated by Django 6.0.7 on 2026-08-04 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='average_sleep_time',
            field=models.TimeField(blank=True, null=True, verbose_name='평균 취침시간'),
        ),
        migrations.AddField(
            model_name='patient',
            name='average_wake_time',
            field=models.TimeField(blank=True, null=True, verbose_name='평균 기상시간'),
        ),
        migrations.AddField(
            model_name='patient',
            name='is_smoker',
            field=models.BooleanField(blank=True, null=True, verbose_name='흡연 여부'),
        ),
        migrations.AddField(
            model_name='patient',
            name='meal_pattern',
            field=models.CharField(blank=True, choices=[('regular', '규칙적'), ('irregular', '불규칙적'), ('less_than_2', '하루 2끼 이하'), ('skip', '식사를 자주 거름')], max_length=20, null=True, verbose_name='식사 습관'),
        ),
    ]
