# Generated by Django 6.0.7 on 2026-08-06 02:25

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_average_sleep_time_patient_average_wake_time_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('intent', models.CharField(blank=True, choices=[('부작용', '부작용'), ('복약', '복약'), ('일반질문', '일반질문')], max_length=10)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', '진행중'), ('closed', '종료')], default='active', max_length=10)),
                ('summary', models.TextField(blank=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_sessions', to='patients.patient')),
            ],
            options={
                'db_table': 'chat_session',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('log_type', models.CharField(choices=[('free_text', '자유문진'), ('scale', '척도')], max_length=20)),
                ('chief_complaint', models.TextField()),
                ('onset', models.CharField(blank=True, max_length=200)),
                ('symptom_pattern', models.TextField(blank=True)),
                ('severity', models.CharField(blank=True, max_length=50)),
                ('aggravating_factor', models.TextField(blank=True)),
                ('scale_name', models.CharField(blank=True, max_length=50)),
                ('scale_score', models.IntegerField(blank=True, null=True)),
                ('keyword', models.CharField(blank=True, max_length=255)),
                ('summary', models.TextField(blank=True)),
                ('suspected_drugs', models.JSONField(blank=True, null=True)),
                ('reported_at', models.DateTimeField()),
                ('chat_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.chatsession')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
                ('prescription', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='patients.prescription')),
            ],
            options={
                'db_table': 'symptom_log',
                'indexes': [models.Index(fields=['patient', '-reported_at'], name='idx_patient_time')],
            },
        ),
    ]
