# Generated by Django 6.0.7 on 2026-08-06 06:19

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_chatsession_symptomlog'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='id',
        ),
        migrations.AlterField(
            model_name='chatsession',
            name='session_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
